# Generated by Django 4.2 on 2024-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(default='+7')),
                ('balans', models.TextField()),
                ('sale', models.TextField()),
            ],
        ),
    ]
