# Generated by Django 4.2 on 2024-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Продан', 'В продаже'), ('Ожидает подтверждения', 'Не выполнен')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.CharField(max_length=100)),
            ],
        ),
    ]
