# Generated by Django 4.2 on 2024-02-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Продан', 'Продан'), ('В продаже', 'В продаже'), ('Ожидает подтверждения', 'Ожидает подтверждения'), ('Не выполнен', 'Не выполнен'), ('Проблемный', 'Проблемный')], max_length=30),
        ),
    ]
