# Generated by Django 4.2 on 2024-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_descr', models.TextField()),
                ('image', models.ImageField(upload_to='products_images')),
                ('product_town', models.TextField()),
                ('product_distr', models.TextField()),
                ('product_addr', models.TextField()),
                ('product_comm', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_employee', models.TextField()),
            ],
        ),
    ]
