# Generated by Django 4.2 on 2024-02-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_product_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='user',
        ),
    ]
