# Generated by Django 4.2 on 2024-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0008_remove_product_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products_images'),
            preserve_default=False,
        ),
    ]
