# Generated by Django 4.2 on 2024-02-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0011_product_product_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_addr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_comm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_descr',
        ),
    ]
