# Generated by Django 4.2 on 2024-02-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0014_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_descr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
