# Generated by Django 4.2 on 2024-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0015_product_product_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_comm',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
