# Generated by Django 4.2 on 2024-02-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0016_product_product_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_addr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
