# Generated by Django 4.2 on 2024-02-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0017_product_product_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balans',
            new_name='balans_prihod',
        ),
        migrations.AddField(
            model_name='user',
            name='balans_rashod',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
