# Generated by Django 4.2 on 2024-02-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0018_rename_balans_user_balans_prihod_user_balans_rashod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balans',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
