# Generated by Django 4.2 on 2024-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0019_user_balans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balans_prihod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balans_rashod',
            field=models.IntegerField(default=0),
        ),
    ]
