# Generated by Django 4.2 on 2024-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0020_alter_user_balans_alter_user_balans_prihod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('G', 'Продан'), ('Y', 'В продаже'), ('O', 'Ожидает подтверждения'), ('R', 'Не выполнен'), ('H', 'Проблемный')], max_length=30),
        ),
    ]
