# Generated by Django 4.2 on 2024-06-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0021_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_accessible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('client_id', models.IntegerField()),
                ('quantity_orders', models.IntegerField()),
                ('quantity_problems_order', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('balans', models.IntegerField()),
                ('status', models.CharField(choices=[('Активный', 'Активный'), ('Не активный', 'Не активный'), ('Все клиенты', 'Все клиенты'), ('Заблокированный', 'Заблокированный')], max_length=30)),
                ('orders_buy', models.TextField()),
                ('orders_buy_sum', models.TextField()),
                ('orders_problem_kolvo', models.IntegerField()),
                ('orders_problem_sum', models.IntegerField()),
                ('procent_orders_problem', models.IntegerField()),
                ('telegram', models.TextField()),
                ('skidka', models.IntegerField()),
                ('Email', models.TextField()),
                ('role', models.CharField(choices=[('Сотрудник', 'Сотрудник'), ('Менеджер', 'Менеджер'), ('Технический сотрудник', 'Технический сотрудник'), ('Администратор магазина', 'Администратор магазина')], max_length=60)),
                ('otmen_zakaz', models.IntegerField()),
                ('zakaz_ojid_oplat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Sposob', models.TextField()),
                ('Vid_oplata', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(unique=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('quantity_orders', models.IntegerField(blank=True, null=True)),
                ('quantity_problems_order', models.IntegerField(blank=True, null=True)),
                ('telegram', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Активный', 'Активный'), ('Не активный', 'Не активный'), ('Все клиенты', 'Все клиенты'), ('Заблокированный', 'Заблокированный')], max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skidka', models.IntegerField(blank=True, null=True)),
                ('orders_problem_sum', models.IntegerField(blank=True, null=True)),
                ('orders_zagruz_sum', models.IntegerField(blank=True, null=True)),
                ('kolvo_tovarov', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Сотрудник', 'Сотрудник'), ('Менеджер', 'Менеджер'), ('Технический сотрудник', 'Технический сотрудник'), ('Администратор магазина', 'Администратор магазина')], max_length=60)),
                ('password', models.TextField(blank=True, null=True)),
                ('access_pages', models.ManyToManyField(to='site1.accesspage')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tovar', models.CharField(max_length=156)),
                ('status', models.CharField(choices=[('G', 'Продан'), ('O', 'Ожидает подтверждения'), ('R', 'Отменён'), ('H', 'Проблемный')], max_length=30)),
                ('product_id', models.TextField(unique=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_card', models.CharField(max_length=156)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='orders_images')),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField()),
                ('order_date', models.DateField()),
                ('order_quant', models.IntegerField()),
                ('order_summ', models.IntegerField()),
                ('order_payment', models.TextField()),
                ('order_addr', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.client')),
                ('order_itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.product')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('districts', models.ManyToManyField(to='site1.district')),
            ],
        ),
    ]
