# Generated by Django 4.2 on 2024-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0022_accesspage_client_district_name_payment_user_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='balans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
