# Generated by Django 4.2 on 2024-07-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0023_team_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='comment',
            field=models.CharField(default=1, max_length=156),
            preserve_default=False,
        ),
    ]
