# Generated by Django 4.2 on 2024-07-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0024_team_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='prihod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='rashod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
