# Generated by Django 4.2 on 2024-07-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0025_team_prihod_team_rashod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
