# Generated by Django 4.2 on 2024-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0026_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_addr',
            field=models.TextField(verbose_name='Характеристики'),
        ),
    ]
