# Generated by Django 4.2 on 2024-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0027_alter_product_product_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
