# Generated by Django 4.2 on 2024-08-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0029_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
