# Generated by Django 4.2 on 2024-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0031_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
