# Generated by Django 4.2 on 2024-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0034_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
