# Generated by Django 4.2 on 2024-08-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0035_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('G', 'Продан'), ('O', 'Ожидает подтверждения'), ('R', 'Отменён'), ('H', 'Проблемный'), ('F', 'Создан')], max_length=30),
        ),
    ]
