# Generated by Django 4.2 on 2024-08-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0036_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.user'),
        ),
    ]
