# Generated by Django 4.2 on 2024-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0039_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.TextField(),
        ),
    ]
