from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
urlpatterns = [
    path('home', login_required(views.home), name='home'),
    path('cards-page/<int:product_id>/', views.cards_product, name='cards_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('profile/<int:team_id>/', views.profile, name='profile'),
    path('profile_polz/<int:user_id>/', views.profile_polz, name='profile_polz'),
    path('profile_polz2/<int:user_id>/', views.profile_polz2, name='profile_polz2'),
    path('profile_balans/<int:user_id>/', views.profile_balans, name='profile_balans'),
    path('profile_balans2/<int:user_id>/', views.profile_balans2, name='profile_balans2'),
    path('profile_balans3/<int:user_id>/', views.profile_balans3, name='profile_balans3'),
    path('profile_balans4/<int:user_id>/', views.profile_balans4, name='profile_balans4'),
    path('profile_sotrudnik/<int:team_id>/', views.profile_sotrudnik, name='profile_sotrudnik'),
    path('index', views.index, name='index'),
    path('product-availability', views.product_availability, name='product_availability'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('product-base', views.add_product, name='product_base'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('redact-address/<int:pk>/', views.UserRedactView.as_view(), name='redact'),
    path('site1/products/<str:product_name>/', views.get_product_info, name='get_product_info'),
    path('site1/city/<str:product_city>/', views.get_product_info1, name='get_product_info1'),
    path('site1/payment_method/<str:product_payment_method>/', views.get_product_info2, name='get_product_info2'),
    path('site1/employee/<str:product_employee>/', views.get_product_info3, name='get_product_info3'),
    path('choose-city/', views.update_city, name='update_city'),
    path('cancel_sale/<int:profile_id>/', views.cancel_sale, name='cancel_sale'),
    path('team', views.team, name='team'),
    path('team-workers/<int:client_id>/', views.team_workers, name='team_workers'),
    path('payments', views.payment, name='payment'),
    path('clients', views.clients, name='clients'),
    path('team-workers2/<int:client_id>/', views.team_workers2, name='team_workers2'),
    path('client-profile/<int:client_id>/', views.clients_profile, name='client_profile'),
    path('orders', views.orders, name='orders'),
    path('orders-page/<int:order_id>/', views.order_page, name='orders_page'),
    path('form-team', views.team_form, name='team_form'),
    path('clients/<int:client_id>/edit/', views.client_redact, name='client_redact'),
    path('save_access/<int:client_id>/', views.save_access, name='save_access'),
    path('', views.login_view, name='login'),
    path('clients/<int:client_id>/block/', views.block_client, name='block_client'),
    path('clients/<int:client_id>/unblock/', views.unblock_client, name='unblock_client'),
    path('new-order/<int:order_id>/', views.new_order, name='new_order'),
    path('home_page', views.home_page, name='home_page'),
    path('home_page_plit', views.home_page_plit, name='home_page_plit'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order_polz', views.order_polz, name='order_polz'),
    path('pay_order', views.pay_order, name='pay_order')
]

